"""empty message

Revision ID: 138bb413e10e
Revises: 
Create Date: 2023-03-13 15:33:34.580831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138bb413e10e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('administrator', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'administrator')
    # ### end Alembic commands ###
